name: "[WORKFLOW] Deploy Markdown to GitHub Pages"

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '.github/**'

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: "[STEP] Checkout Repository via Action"
        uses: actions/checkout@main
      - name: Markdown to GitHub Pages Deploy
        uses: Godners-Code/deploy-markdown-pages@main
        with:
          page-title: "Voluptus Research"
